languages =
{
	ab:"Аҧсуа бызшәа",
	ace:"Achinese",
	ach:"Acoli",
	ada:"Adangme",
	ady:"Adygei; Adyghe",
	aa:"Afar",
	afh:"Afrihili",
	af:"Afrikaans",
	afa:"Afro-Asiatic (Other)",
	ak:"Akan",
	akk:"Akkadian",
	sq:"Albanian",
	ale:"Aleut",
	alg:"Algonquian languages",
	tut:"Altaic (Other)",
	am:"አማርኛ",
	apa:"Apache languages",
	ar:"Arabic",
	an:"Aragonese",
	arc:"בְּאַרָמִית",
	arp:"Arapaho",
	arn:"Araucanian",
	arw:"Arawak",
	hy:"Հայերեն",
	art:"Artificial (Other)",
	as:"অসিময়া",
	ath:"Athapascan languages",
	aus:"Australian languages",
	map:"Austronesian (Other)",
	av:"Avaric",
	ae:"Avestan",
	awa:"Awadhi",
	ay:"Aymará",
	az:"Azərbaycanca",
	ast:"Bable; Asturian",
	ban:"Balinese",
	bat:"Baltic (Other)",
	bal:"Baluchi",
	bm:"Bambara",
	bai:"Bamileke languages",
	bad:"Banda",
	bnt:"Bantu (Other)",
	bas:"Basa",
	ba:"Bashkir",
	eu:"Basque",
	btk:"Batak (Indonesia)",
	bej:"Beja",
	be:"Belarusian",
	bem:"Bemba",
	bn:"Bengali",
	ber:"Berber (Other)",
	bho:"Bhojpuri",
	bh:"Bihari",
	bik:"Bikol",
	byn:"Bilin; Blin",
	bin:"Bini",
	bi:"Bislama",
	nb:"Norwegian Bokmål; Bokmål, Norwegian",
	bs:"Bosanski",
	bra:"Braj",
	br:"Breton",
	bug:"Buginese",
	bg:"Български",
	bua:"Buriat",
	my:"Burmese",
	cad:"Caddo",
	car:"Carib",
	es:"Español",
	ca:"Valencian; Catalan",
	cau:"Caucasian (Other)",
	ceb:"Cebu",
	cel:"Celtic (Other)",
	cai:"Central American Indian (Other)",
	chg:"Chagatai",
	cmc:"Chamic languages",
	ch:"Chamorro",
	ce:"Chechen",
	chr:"Cherokee",
	ny:"Nyanja; Chichewa; Chewa",
	chy:"Cheyenne",
	chb:"Chibcha",
	zh:"官话",
	chn:"汉语/中文",
	chp:"Chipewyan",
	cho:"Choctaw",
	za:"Zhuang; Chuang",
	cu:"Old Slavonic; Church Slavonic; Old Bulgarian; Church Slavic; Old Church Slavonic",
	chk:"Chuukese",
	cv:"Chuvash",
	nwc:"Old Newari; Classical Newari",
	cop:"Coptic",
	kw:"Cornish",
	co:"Corsican",
	cr:"ᓂᐦᔭᐘᒃ",
	mus:"Creek",
	crp:"Creoles and pidgins (Other)",
	cpe:"Creoles and pidgins, English-based (Other)",
	cpf:"Creoles and pidgins, French-based (Other)",
	cpp:"Creoles and pidgins, Portuguese-based (Other)",
	crh:"Crimean Tatar; Crimean Turkish",
	hr:"hrvatski",
	cus:"Cushitic (Other)",
	cs:"Čeština",
	dak:"Dakota",
	da:"Dansk",
	dar:"Dargwa",
	day:"Dayak",
	del:"Delaware",
	din:"Dinka",
	dv:"Divehi",
	doi:"Dogri",
	dgr:"Dogrib",
	dra:"Dravidian (Other)",
	dua:"Duala",
	nl:"Nederlands",
	dum:"Dutch, Middle (ca. 1050-1350)",
	dyu:"Dyula",
	dz:"༄༅ཇོ༹ང་ཁ",
	efi:"Efik",
	egy:"Egyptian (Ancient)",
	eka:"Ekajuk",
	elx:"Elamite",
	en:"English",
	enm:"English, Middle (1100-1500)",
	ang:"English, Old (ca.450-1100)",
	myv:"Erzya",
	eo:"Esperanto",
	et:"Eesti",
	ee:"Éwé",
	ewo:"Ewondo",
	fan:"Fang",
	fat:"Fanti",
	fo:"Faroese",
	fj:"Fijian",
	fi:"Suomea",
	fiu:"Finno-Ugrian (Other)",
	fon:"Fon",
	fr:"Français",
	frm:"French, Middle (ca.1400-1600)",
	fro:"French, Old (842-ca.1400)",
	fy:"Frisian",
	fur:"Friulian",
	ff:"Fulah",
	gaa:"Ga",
	gd:"Scottish Gaelic; Gaelic",
	gl:"Gallegan",
	lg:"Ganda",
	gay:"Gayo",
	gba:"Gbaya",
	gez:"Geez",
	ka:"ქართული",
	de:"Deutsch",
	nds:"Saxon, Low; German, Low; Low Saxon; Low German",
	gmh:"German, Middle High (ca.1050-1500)",
	goh:"German, Old High (ca.750-1050)",
	gem:"Germanic (Other)",
	ki:"Kikuyu; Gikuyu",
	gil:"Gilbertese",
	gon:"Gondi",
	gor:"Gorontalo",
	got:"Gothic",
	grb:"Grebo",
	grc:"Greek, Ancient (to 1453)",
	el:"Ελληνικά",
	kl:"Kalaallisut; Greenlandic",
	gn:"Guarani",
	gu:"Gujarati",
	gwi:"Gwich´in",
	hai:"Haida",
	ht:"Krèyol",
	ha:"Hausa",
	haw:"Hawaiian",
	he:"עברית",
	hz:"Herero",
	hil:"Hiligaynon",
	him:"Himachali",
	hi:"Hindi",
	ho:"Hiri Motu",
	hit:"Hittite",
	hmn:"Hmong",
	hu:"Magyar",
	hup:"Hupa",
	iba:"Iban",
	is:"íslenska",
	io:"Ido",
	ig:"Igbo",
	ijo:"Ijo",
	ilo:"Iloko",
	smn:"Inari Sami",
	inc:"Indic (Other)",
	ine:"Indo-European (Other)",
	id:"Bahasa Indonesia",
	inh:"гӀалгӀайн мотт",
	ia:"Interlingua (International Auxiliary Language Association)",
	ie:"Interlingue",
	iu:"Inuktitut",
	ik:"Inupiaq",
	ira:"Iranian (Other)",
	ga:"Gaeilge",
	mga:"Irish, Middle (900-1200)",
	sga:"Irish, Old (to 900)",
	iro:"Iroquoian languages",
	it:"Italiano",
	ja:"日本語",
	jv:"Javanese",
	jrb:"Judeo-Arabic",
	jpr:"Judeo-Persian",
	kbd:"Kabardian",
	kab:"Kabyle",
	kac:"Kachin",
	xal:"Kalmyk",
	kam:"Kamba",
	kn:"Kannada",
	kr:"Kanuri",
	krc:"Karachay-Balkar",
	kaa:"Kara-Kalpak",
	kar:"Karen",
	ks:"Kashmiri",
	csb:"Kashubian",
	kaw:"Kawi",
	kk:"қазақша",
	kha:"Khasi",
	km:"Khmer",
	khi:"Khoisan (Other)",
	kho:"Khotanese",
	kmb:"Kimbundu",
	rw:"Kinyarwanda",
	ky:"Kirghiz",
	tlh:"tlhlngan-Hol; Klingon",
	kv:"Komi",
	kg:"Kongo",
	kok:"Konkani",
	ko:"Korean",
	kos:"Kosraean",
	kpe:"Kpelle",
	kro:"Kru",
	kj:"Kwanyama, Kuanyama",
	kum:"Kumyk",
	ku:"Kurdî",
	kru:"Kurukh",
	kut:"Kutenai",
	lad:"Ladino",
	lah:"Lahnda",
	lam:"Lamba",
	lo:"Lao",
	la:"Latviešu",
	lv:"latviešu valoda",
	lb:"Lëtzebuergesch ",
	lez:"Lezghian",
	li:"Limburgish; Limburger; Limburgan",
	ln:"Lingala",
	lt:"Lietuvių",
	jbo:"Lojban",
	dsb:"Lower Sorbian",
	loz:"Lozi",
	lu:"Luba-Katanga",
	lua:"Luba-Lulua",
	lui:"Luiseno",
	smj:"Lule Sami",
	lun:"Lunda",
	luo:"Luo (Kenya and Tanzania)",
	lus:"Lushai",
	mk:"Makedonski",
	mad:"Madurese",
	mag:"Magahi",
	mai:"Maithili",
	mak:"Makasar",
	mg:"Malagasy",
	ms:"Malay",
	ml:"Марий",
	mt:"Malti",
	mnc:"Manchu",
	mdr:"Mandar",
	man:"Mandingo",
	mni:"Manipuri",
	mno:"Manobo languages",
	gv:"Manx",
	mi:"Maori",
	mr:"Marathi",
	chm:"Mari",
	mh:"Marshallese",
	mwr:"Marwari",
	mas:"Masai",
	myn:"Mayan languages",
	men:"Mende",
	mic:"Micmac",
	min:"Minangkabau",
	mis:"Miscellaneous languages",
	moh:"Mohawk",
	mdf:"Moksha",
	mo:"Moldavian",
	mkh:"Mon-Khmer (Other)",
	lol:"Mongo",
	mn:"Mongolian",
	mos:"Mossi",
	mul:"Multilingual",
	mun:"Munda languages",
	nah:"Nahuatl",
	na:"Nauru",
	nv:"Diné bizaad",
	nd:"North Ndebele",
	nr:"South Ndebele",
	ng:"Ndonga",
	nap:"Neapolitan",
	ne:"नेपाली",
	"new":"Newari",
	nia:"Nias",
	nic:"Niger-Kordofanian (Other)",
	ssa:"Nilo-Saharan (Other)",
	niu:"Niuean",
	nog:"Nogai",
	non:"Norse, Old",
	nai:"North American Indian (Other)",
	se:"Northern Sami",
	no:"norsk",
	nn:"Nynorsk, Norwegian; Norwegian Nynorsk",
	nub:"Nubian languages",
	nym:"Nyamwezi",
	nyn:"Nyankole",
	nyo:"Nyoro",
	nzi:"Nzima",
	oc:"Provençal; Occitan (post 1500)",
	oj:"Ojibwa",
	or:"Oriya",
	om:"Oromo",
	osa:"Osage",
	os:"Ossetic; Ossetian",
	oto:"Otomian languages",
	pal:"Pahlavi",
	pau:"Palauan",
	pi:"Pali",
	pam:"Pampanga",
	pag:"Pangasinan",
	pa:"Punjabi; Panjabi",
	pap:"Papiamento",
	paa:"Papuan (Other)",
	fa:"Persian",
	peo:"Persian, Old (ca.600-400 B.C.)",
	phi:"Philippine (Other)",
	phn:"Phoenician",
	pon:"Pohnpeian",
	pl:"Polski",
	pt:"Português",
	pra:"Prakrit languages",
	pro:"Provençal, Old (to 1500)",
	ps:"Pushto",
	qu:"Quechua",
	rm:"Raeto-Romance",
	raj:"Rajasthani",
	rap:"Rapanui",
	rar:"Rarotongan",
	qaa:"Reserved for local use",
	roa:"Romance (Other)",
	ro:"Română",
	rom:"Romany",
	rn:"Rundi",
	ru:"Русский",
	sal:"Salishan languages",
	sam:"Samaritan Aramaic",
	smi:"Sami languages (Other)",
	sm:"Samoan",
	sad:"Sandawe",
	sg:"Sango",
	sa:"Sanskrit",
	sat:"Santali",
	sc:"Sardinian",
	sas:"Sasak",
	sco:"Gàidhlig",
	sel:"Selkup",
	sem:"Semitic (Other)",
	sr:"српски",
	srr:"Serer",
	shn:"Shan",
	sn:"Shona",
	ii:"Sichuan Yi",
	sid:"Sidamo",
	sgn:"Sign languages",
	bla:"Siksika",
	sd:"िसनिध,سنڗي",
	si:"Sinhalese",
	sit:"Sino-Tibetan (Other)",
	sio:"Siouan languages",
	sms:"Skolt Sami",
	den:"Slave (Athapascan)",
	sla:"Slavic (Other)",
	sk:"Slovenčina",
	sl:"slovenščina",
	sog:"Sogdian",
	so:"Soomaali",
	son:"Songhai",
	snk:"Soninke",
	wen:"Sorbian languages",
	nso:"Sotho, Northern",
	st:"Sotho, Southern",
	sai:"South American Indian (Other)",
	sma:"Southern Sami",
	suk:"Sukuma",
	sux:"Sumerian",
	su:"Sundanese",
	sus:"Susu",
	sw:"kiSwahili",
	ss:"Swati",
	sv:"Svenska",
	syr:"Syriac",
	tl:"Taga",
	ty:"Tahitian",
	tai:"Tai (Other)",
	tg:"Tajik",
	tmh:"Tamashek",
	ta:"Tamil",
	tt:"Tatar",
	te:"Telugu",
	ter:"Tereno",
	tet:"Tetum",
	th:"ภาษาไทย",
	bo:"Tibetan",
	tig:"Tigre",
	ti:"Tigrinya",
	tem:"Timne",
	tiv:"Tiv",
	tli:"Tlingit",
	tpi:"Tok Pisin",
	tkl:"Tokelau",
	tog:"chiTonga",
	to:"Tonga (Tonga Islands)",
	tsi:"Tsimshian",
	ts:"xiTsonga",
	tn:"Tswana",
	tum:"Tumbuka",
	tup:"Tupi languages",
	tr:"Türkçe",
	ota:"Turkish, Ottoman (1500-1928)",
	tk:"Turkmen",
	tvl:"Tuvalu",
	tyv:"Tuvinian",
	tw:"Twi",
	udm:"Udmurt",
	uga:"Ugaritic",
	ug:"ﺋۇيغۇر",
	uk:"Український",
	umb:"Umbundu",
	und:"Undetermined",
	hsb:"Upper Sorbian",
	ur:"اُردو",
	uz:"Ўзбек",
	vai:"Vai",
	ve:"tshiVenda",
	vi:"Tiếng Việt",
	vo:"Volapük",
	vot:"vad'd'a tšeeli",
	wak:"Wakashan languages",
	wal:"Walamo",
	wa:"Walloon",
	war:"Waray",
	was:"Washo",
	cy:"Welsh",
	wo:"Wollof",
	xh:"Xhosa",
	sah:"Yakut",
	yao:"Yao",
	yap:"Yapese",
	yi:"ייִדיש",
	yo:"Yorùbá",
	ypk:"Yupik languages",
	znd:"Zande",
	zap:"Zapotec",
	zen:"Zenaga",
	zu:"Zulu",
	zun:"Zuni",
	bx:"Brusseleer",
	bl:"Bilingue"
};